# Generated by Django 4.2.5 on 2023-10-06 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])])),
            ],
        ),
    ]
